include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

  exclude:
    - lib/**.g.dart
    - test/**.mocks.dart

  errors:
    deprecated_member_use: ignore # TODO: Turn on after Flutter-2.5 update lands to see deprecation warnings!

    # TEMPORARILY DEACTIVATED!
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_constructors: ignore
    prefer_const_constructors_in_immutables: ignore

linter:
  rules:

    # STYLE
    directives_ordering: true # do
    lines_longer_than_80_chars: true # avoid

    # DOCUMENTATION
    package_api_docs: true # do
    public_member_api_docs: false # do
    # comment_references: true # Unused because https://github.com/dart-lang/sdk/issues/36974

    # USAGE
    prefer_relative_imports: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_lambdas: true
    # unnecessary_getters: true # prefer # Disabled pending fix: https://github.com/dart-lang/linter/issues/23
    prefer_expression_function_bodies: true # consider
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true

    # DESIGN
    use_to_and_as_if_applicable: true
    one_member_abstracts: true
    avoid_classes_with_only_static_members: true
    prefer_mixin: true
    use_setters_to_change_properties: true
    avoid_setters_without_getters: true
    avoid_returning_null: true
    avoid_returning_this: true
    type_annotate_public_apis: true
    omit_local_variable_types: true
    avoid_types_on_closure_parameters: true
    avoid_private_typedef_functions: true
    avoid_positional_boolean_parameters: true
    avoid_equals_and_hash_code_on_mutable_classes: true

    # ERROR
    avoid_dynamic_calls: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    # diagnostic_describe_all_properties: true
    invariant_booleans: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unsafe_html: true
    use_build_context_synchronously: true

    # PUB
    depend_on_referenced_packages: true

    # STYLE PROPOSAL
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    join_return_with_assignment: true
    missing_whitespace_between_adjacent_strings: true
    noop_primitive_operations: true
    no_default_cases: true
    null_check_on_nullable_type_parameter: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_constructors_over_static_methods: true
    # prefer_double_quotes: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_null_aware_method_calls: true
    # prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    # sort_constructors_first: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    unnecessary_await_in_return: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_string_buffers: true

dart_code_metrics:

  rules:
    # Common
    avoid-missing-enum-constant-in-map: true
    avoid-nested-conditional-expressions:
      acceptable-level: 2
    avoid-throw-in-catch-block: true
    avoid-unnecessary-type-cast: true
    avoid-unused-parameters: true
    avoid-unnecessary-type-assertions: true
    binary-expression-operand-order: true
    double-literal-format: true
    # member-ordering: true
    # member-ordering-extended: true
    # newline-before-return: true
    no-boolean-literal-compare: true
    no-empty-block: true
    # no-equal-arguments: true
    no-equal-then-else: true
    no-object-declaration: true
    prefer-conditional-expressions: true
    # prefer-correct-identifier-length: true
    prefer-correct-type-name: true
    prefer-first: true
    prefer-last: true
    # prefer-match-file-name: true
    prefer-trailing-comma: true

    # Flutter
    always-remove-listener: true
    avoid-unnecessary-setstate: true
    avoid-wrapping-in-padding: true
    prefer-const-border-radius: true
    prefer-extracting-callbacks: true
    prefer-single-widget-per-file: true
